### ISSUE TITLE
schematic.py: Blockstate Property Bug & Needs adjustment:

### ISSUE THREAD

**Issue by IS1-4MJ** [SmylerMC/litemapy#2]
schematic.py line 300: property optional parameter is both initialized as an object, meaning all BlockState objects will wind up with the same properties after editing them, and Blockstate.property string contents must be initialized using nbtlib.tag's String tag for properties to effectively translate into the game without crashing the program.

Recreation: Try making a Minecraft:note_block with a harp instrument and a note=11. Using the constructor, this does nothing. Altering the properties in the dictionary using python strings crashes the program during processing in nbt.py's save function. Turning these strings into nbtlib.tag Strings solved the bug.

![image](https://user-images.githubusercontent.com/30614712/85960470-b954b200-b971-11ea-9ef4-b51a3ae3369e.png)

**Comment by SmylerMC** [comment]
Actually the optional parameter does nothing right now as it is never assigned to self.properties, which is indeed a bug:
`    def __init__(self, blockid, properties={}):
        self.blockid = blockid
        self.properties = {}
`
It is intended that block states are mutable, including their properties. If you want a to change a block's properties without changing the other's you need to create a new block state for it.
I will look into the string problem.

**Comment by IS1-4MJ** [comment]
I remember having fixed this so it worked for my purposes... let me post here in a moment what i did to fix it:

**Comment by IS1-4MJ** [comment]
![image](https://user-images.githubusercontent.com/30614712/94372830-0eb67180-00cf-11eb-8bcd-5bb0a6c127d8.png)
This is the workaround I used, that worked for setting note block music notes as different from one another.

**Comment by Peter-Crawley** [comment]
Is a fix coming for this anytime soon?
