### ISSUE TITLE
Schematic.load() fails with schematics containing tile entities

### ISSUE THREAD

**Issue by UpsideDownFoxxo** [SmylerMC/litemapy#25]
Whenever a schematic contains a tile entity, the program will exit with the following error:
```
File "project\venv\lib\site-packages\litemapy\schematic.py", line 321, in fromnbt
    block = TileEntity.fromnbt(tentity)
AttributeError: type object 'TileEntity' has no attribute 'fromnbt'
```

Tested with the following schematic and code:
`schem = Schematic.load("test.litematic")`

[test.zip](https://github.com/SmylerMC/litemapy/files/10045617/test.zip)
(contains a single shulker box without items inside)

**Comment by SmylerMC** [comment]
I cannot reproduce your issue with the provided schematic.

Can you check that you are using the latest version of Litemapy (0.7.2b0) ?

**Comment by UpsideDownFoxxo** [comment]
Huh. I Installed it through PIP, it gave me version 0.3.1a0
I will try it out with the new version then

**Comment by UpsideDownFoxxo** [comment]
Alright, the new version appears to fix it. Pip seems to want to install the version mentioned above, but when downloading it from Github it works correctly
