### ISSUE TITLE
IndexError in Entity class due to inconsistent handling of 'Rotation' data

### ISSUE THREAD

**Issue by Kingburrito777** [SmylerMC/litemapy#50]
---
title: IndexError in Entity class due to inconsistent handling of 'Rotation' data
labels: bug
---

## Description
There's an inconsistency in the `Entity` class in how it handles the 'Rotation' data. The class initializes 'Rotation' with two elements if it's not present, but later attempts to access a third element, causing an IndexError.

## Code Causing the Issue
In the `Entity` class (`litemapy/minecraft.py`):

```python
class Entity:
    def __init__(self, str_or_nbt: Union[str, Compound]) -> None:
        # ...
        if 'Rotation' not in keys:
            self._data['Rotation'] = List[Double]([Double(0.), Double(0.)])
        # ...
        rotation = [float(coord) for coord in self._data['Rotation']]
        self._rotation = (rotation[0], rotation[1], rotation[2])  # This line causes the error
        # ...
```

## Error Message
```
IndexError: list index out of range
```

## Expected Behavior
The `Entity` class should consistently handle 'Rotation' data, either always expecting two elements or always expecting three elements.

## Actual Behavior
The class initializes 'Rotation' with two elements but later attempts to access a third element, causing an IndexError when the third element doesn't exist.

## Possible Solutions
1. Modify the initialization to always include three elements:
   ```python
   if 'Rotation' not in keys:
       self._data['Rotation'] = List[Double]([Double(0.), Double(0.), Double(0.)])
   ```

2. Modify the assignment to `self._rotation` to only use two elements:
   ```python
   self._rotation = (rotation[0], rotation[1])
   ```

3. Use a more flexible approach that works with either two or three elements:
   ```python
   self._rotation = tuple(rotation + [0.0] * (3 - len(rotation)))
   ```

## Additional Context
This issue affects the loading of litematic files that contain entity data. It's possible that different versions of the litematic format or Minecraft itself use different numbers of rotation elements for entities.

## Steps to Reproduce
1. Create a litematic file that includes entity data with only two rotation elements.
2. Attempt to load this file using the `LitematicSchematic.load()` method.

## Environment
- litemapy version: [0.9.0b0]
- Python version: [3.12.4]
- Operating System: [Windows 10]

**Comment by SmylerMC** [comment]
Thank you for reporting this bug.

As far as I know rotations are supposed to have two elements in Minecraft (yaw and pitch). This is what was originally implemented in the constructor. Somewhere along the way, it appears we ended-up considering it as a 3-float tuple instead of a 2-float tuple in almost every place. I don't think that's correct.

**Comment by SmylerMC** [comment]
Hi @Kingburrito777 , do you want to check-out #51 and confirm it fixes your issue?

**Comment by Kingburrito777** [comment]
> Hi @Kingburrito777 , do you want to check-out #51 and confirm it fixes your issue?

I'll do so shortly. I'll be sure to test a few different test cases thanks 
Liam
