### ISSUE TITLE
Issuse of Entity in the litematica file

### ISSUE THREAD

**Issue by albertchen857** [SmylerMC/litemapy#54]
If litematica file have entities in the file will report list out of range. Cause of **Entity Class __init__ function**.  
self._rotation = (rotation[0], rotation[1], rotation[2])  IndexError: list index out of range

**Comment by SmylerMC** [comment]
Hi,
This issue was fixed a few weeks ago (see #51 ), but there hasen't been any releases yet.I will be pushing a 0.10.0b0 version to pypi later today or tomorrow containing the fix.
