### ISSUE TITLE
Is there any way to change a block's properties?

### ISSUE THREAD

**Issue by nouni19** [SmylerMC/litemapy#9]
Is there any function or argument to the class BlockState to change the properties of the block? (Example, which direction a stair or a redstone torch is facing, note in a noteblock...)

**Comment by SmylerMC** [comment]
Hello,
The `BlockState` constructor can take a str => str dictionary as argument to specify properties. For an existing object, those properties can be queried using the bracket syntax.

```python
state = BlockState("minecraft:note_block", properties={"note": "10"})
note = state["note"]
# note now equals "10"
```
